### PR TITLE
[ISSUE-1096] Fix lint and unit test error for resolution to atl-22498

### LINKED ISSUE #1096: 22498 - lint issue with previous fix for lsblk.go
**Describe the bug**
error in lint and unit test from PR #1095 

make lint gets the following error:

```
INFO [runner] linters took 24.048004155s with stages: goanalysis_metalinter: 24.039978211s 
pkg/base/linuxutils/lsblk/lsblk.go:163:68: unnecessary leading newline (whitespace)
```

`make test` error:
```
=== RUN   TestLSBLK_SearchDrivePath_Success
--- FAIL: TestLSBLK_SearchDrivePath_Success (0.00s)
panic:
assert: mock: I don't know what to return because the method call was unexpected.
        Either do Mock.On("RunCmd").Return(...) first, or remove the RunCmd() call.
        This method was unexpected:
                RunCmd(string)
                0: "lsblk  --paths --json --bytes --fs --output NAME,TYPE,SIZE,ROTA,SERIAL,WWN,VENDOR,MODEL,REV,MOUNTPOINT,FSTYPE,PARTUUID"
        at: [executors.go:181 lsblk.go:133 lsblk.go:166 lsblk_test.go:92] [recovered]
        panic:
assert: mock: I don't know what to return because the method call was unexpected.
        Either do Mock.On("RunCmd").Return(...) first, or remove the RunCmd() call.
        This method was unexpected:
                RunCmd(string)
                0: "lsblk  --paths --json --bytes --fs --output NAME,TYPE,SIZE,ROTA,SERIAL,WWN,VENDOR,MODEL,REV,MOUNTPOINT,FSTYPE,PARTUUID"
        at: [executors.go:181 lsblk.go:133 lsblk.go:166 lsblk_test.go:92]
```
**Environment (please complete the following information):**
 - Hardware: [e.g. Dell PowerEdge]
 - OS: [e.g. Ubuntu, run `printf "$(uname -srm)\n$(cat /etc/os-release)\n"`]
 - Version: [e.g. 1.0.0]
Lint eError

**To Reproduce**
```
make lint 
```

**Expected behavior**
It should build

**Screenshots**
look up 

**Additional context**

### PR DESCRIPTION
**Pull request by eddiepavkovic**
### Resolves #1096 
Fixed lint issue from previous #1095 merge 

## PR checklist
- [x] Add link to the issue
- [x] Choose Project
- [x] Choose PR label
- [ ] New unit tests added
- [x] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
https://asd-ecs-jenkins.isus.emc.com/job/csi-custom-build/1006/

Running csi-custom-ci and csi-custom-build

### CODE REVIEW

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 1]
```diff
@@ -161,8 +161,13 @@ func (l *LSBLK) GetBlockDevices(device string) ([]BlockDevice, error) {
 // Receives an instance of drivecrd.Drive struct
 // Returns drive's path based on provided drivecrd.Drive or error if something went wrong
 func (l *LSBLK) SearchDrivePath(drive *api.Drive) (string, error) {
+	// device path might be already set by hwmgr
```
Comment (libzhang) [inline pkg/base/linuxutils/lsblk/lsblk.go:164]: adding this code back seems violate @prasant123 previous fix code intention.   if device is in drive CR,  then the device name in driveCR is returned here,  this might be a wrong name due to device name change.

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /*
-Copyright © 2020 Dell Inc. or its subsidiaries. All Rights Reserved.
+Copyright © 2020-2024 Dell Inc. or its subsidiaries. All Rights Reserved.
 
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
```
Comment (libzhang) [inline pkg/base/linuxutils/lsblk/lsblk.go:5]: to fix the UT error, we may remove the tested case for this part of added back code which was removed in previous PR. 
https://github.com/dell/csi-baremetal/blob/rel/CY2310/pkg/base/linuxutils/lsblk/lsblk_test.go#L88C1-L94C28

File: pkg/base/linuxutils/lsblk/lsblk.go (hunk 1 above)
Comment (eddiepavkovic) [reply pkg/base/linuxutils/lsblk/lsblk.go:164]: ok i'll remove the test case and put back his orig code.
thanks

File: pkg/base/linuxutils/lsblk/lsblk.go (hunk 2 above)
Comment (eddiepavkovic) [reply pkg/base/linuxutils/lsblk/lsblk.go:5]: yep removed it

File: pkg/base/linuxutils/lsblk/lsblk.go (hunk 1 above)
Comment (eddiepavkovic) [reply pkg/base/linuxutils/lsblk/lsblk.go]: @libzhang  - do you have any idea why all the PR checks are no longer on this PR?

**Review by prasant123 — APPROVED** [review]
LGTM

File: pkg/base/linuxutils/lsblk/lsblk.go (hunk 1 above)
Comment (libzhang) [reply pkg/base/linuxutils/lsblk/lsblk.go]: I am not sure,  maybe there is some bug in the our release branch workflow.

**Review by libzhang — APPROVED** [review]
