### PR TITLE
[ISSUE-1145]: use a serial number to compare drives

### LINKED ISSUE #1145: fix failed to create LVM
**Describe the bug**

**Environment (please complete the following information):**
 - Hardware: [e.g. Dell PowerEdge]
 - OS: [e.g. Ubuntu, run `printf "$(uname -srm)\n$(cat /etc/os-release)\n"`]
 - Version: [e.g. 1.0.0]

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by korzepadawid**
### Resolves #1145
Used a serial number to compare drives.

## PR checklist
- [ ] Add link to the issue
- [ ] Choose Project
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
_Provide test details_

### CODE REVIEW

**Review by katarzyna-kulpa — APPROVED** [review]

**Review by IlliaNebeskyi — APPROVED** [review]

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 1]
```diff
@@ -178,17 +178,11 @@ func (l *LSBLK) SearchDrivePath(drive *api.Drive) (string, error) {
...
 		}
 	}
 
-	if device == "" {
-		errMsg := fmt.Errorf("unable to find drive path by SN %s, VID %s, PID %s", sn, vid, pid)
-		return "", errMsg
-	}
-
-	return device, nil
+	errMsg := fmt.Errorf("unable to find drive path by SN %s, VID %s, PID %s", sn, vid, pid)
```
Comment (rafalw82) [inline pkg/base/linuxutils/lsblk/lsblk.go:186]: The message should be rephrased now, it is misleading, now we're searching only by serial number.
Please adjust also function comment accordingly.

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 2]
```diff
@@ -157,16 +157,10 @@ func (l *LSBLK) GetBlockDevices(device string) ([]BlockDevice, error) {
 	return res, nil
 }
 
-// SearchDrivePath if not defined returns drive path based on drive S/N, VID and PID.
+// SearchDrivePath returns drive path based on drive S/N.
 // Receives an instance of drivecrd.Drive struct
 // Returns drive's path based on provided drivecrd.Drive or error if something went wrong
```
Comment (katarzyna-kulpa) [inline pkg/base/linuxutils/lsblk/lsblk.go:162]: it returns now drive's path based on lsblk output not drivecrd

**Review by katarzyna-kulpa — APPROVED** [review]

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 3]
```diff
@@ -157,16 +157,10 @@ func (l *LSBLK) GetBlockDevices(device string) ([]BlockDevice, error) {
...
 func (l *LSBLK) SearchDrivePath(drive *api.Drive) (string, error) {
-	// device path might be already set by hwmgr
-	device := drive.Path
-	if device != "" {
-		return device, nil
-	}
-
 	// try to find it with lsblk
 	lsblkOut, err := l.GetBlockDevices("")
```
[the remark this answers is not in the document]
Comment (katarzyna-kulpa) [reply pkg/base/linuxutils/lsblk/lsblk.go:165]: If serial number is unique then there is no need to call drive manager api. lslkb provides correct information about serial number and we haven't seen any issues with serial number differences between lsblk and drive mgr output.

File: api/v1/constants.go [hunk 4]
```diff
@@ -150,4 +150,10 @@ const (
 	// CSI StorageGroup annotations
 	StorageGroupAnnotationDriveRemovalPrefix = "drive-removal"
 	StorageGroupAnnotationDriveRemovalDone   = "done"
+
+	// CSI Drive Managers
+	DriveManagerLoopback = "loopbackmgr"
```
Comment (katarzyna-kulpa) [inline api/v1/constants.go:155]: let's use DriveMgr naming convention

File: cmd/node/main.go [hunk 5]
```diff
@@ -165,12 +168,19 @@ func main() {
 	defer eventRecorder.Wait()
 
 	wrappedK8SClient := k8s.NewKubeClient(k8SClient, logger, objects.NewObjectLogger(), *namespace)
+
+	driveMgrType, err := getDriveManagerType(wrappedK8SClient, logger)
+	if err != nil {
+		logger.Fatalf("fail to infer driver manager type: %v", err)
```
Comment (katarzyna-kulpa) [inline cmd/node/main.go:174]: maybe change the slogan to: drive mgr not defined

File: cmd/node/main.go [hunk 6]
```diff
@@ -384,3 +394,40 @@ func prepareWbtWatcher(client k8sClient.Client, eventsRecorder *events.Recorder,
...
 }
+
+// getDriverManagerType retrieves the type of the driver manager used by the pod.
+// It searches for a container named "drivemgr" in the specified pod and
+// determines the driver manager type based on its image.
+//
+// If the driver manager type is found, it returns the type as a string and nil error.
+// If the pod or container is not found, it returns an empty string and an error indicating
+// the failure reason.
+func getDriveManagerType(client k8sClient.Client, logger *logrus.Logger) (string, error) {
```
Comment (katarzyna-kulpa) [inline cmd/node/main.go:405]: let's use DriveMgr naming convention

File: cmd/node/main.go [hunk 7]
```diff
@@ -384,3 +394,40 @@ func prepareWbtWatcher(client k8sClient.Client, eventsRecorder *events.Recorder,
...
+	pod := corev1.Pod{}
+	if err := client.Get(context.Background(), k8sClient.ObjectKey{Name: os.Getenv("POD_NAME"), Namespace: *namespace}, &pod); err != nil {
+		return "unable to find pod", err
```
Comment (katarzyna-kulpa) [inline cmd/node/main.go:408]: add pod name to the error msg

File: cmd/node/main.go [hunk 8]
```diff
@@ -384,3 +394,40 @@ func prepareWbtWatcher(client k8sClient.Client, eventsRecorder *events.Recorder,
...
+	}
+	return findDriverManager(pod, logger)
+}
+
+func findDriverManager(pod corev1.Pod, logger *logrus.Logger) (string, error) {
```
Comment (katarzyna-kulpa) [inline cmd/node/main.go:413]: DriveMgr

File: cmd/node/main.go [hunk 9]
```diff
@@ -384,3 +394,40 @@ func prepareWbtWatcher(client k8sClient.Client, eventsRecorder *events.Recorder,
...
+	for _, c := range pod.Spec.Containers {
```
Comment (katarzyna-kulpa) [inline cmd/node/main.go:414]: have you consider using a map  to store the associations between driver manager types and their corresponding image strings? it will simplify the code. Example from codeium:

 // Define a map to store the associations between driver manager types and their corresponding image strings
var driverManagerImages = map[string]string{
	v1.DriveManagerLoopback: v1.DriveManagerLoopbackImage,
	v1.DriveManagerHal:     v1.DriveManagerHalImage,
	v1.DriveManagerBase:    v1.DriveManagerBaseImage,
	v1.DriveManagerIDRAC:   v1.DriveManagerIDRACImage,
}

// ...

for _, c := range pod.Spec.Containers {
	if c.Name == "drivemgr" {
		logger.Debugf("found a driver manager's image: %s", c.Image)
		for driverManagerType, image := range driverManagerImages {
			if strings.Contains(c.Image, image) {
				return driverManagerType, nil
			}
		}
		logger.Errorf("unknown driver manager type for image: %s", c.Image)
	}
}

**Review by katarzyna-kulpa — CHANGES_REQUESTED** [review]

File: cmd/node/main.go (hunk 9 above)
Comment (korzepadawid) [reply cmd/node/main.go:420]: Great point!

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 10]
```diff
@@ -175,20 +170,18 @@ func (l *LSBLK) SearchDrivePath(drive *api.Drive) (string, error) {
...
-		errMsg := fmt.Errorf("unable to find drive path by SN %s, VID %s, PID %s", sn, vid, pid)
-		return "", errMsg
+	// device path might be already set by hwmgr
+	if drive.Path != "" {
+		l.log.Warnf("unable to find a drive path by a given SN: %s, using a device path: %s", sn, drive.Path)
+		return drive.Path, nil
 	}
 
-	return device, nil
+	errMsg := fmt.Errorf("unable to find drive path by SN %s", sn)
```
Comment (katarzyna-kulpa) [inline pkg/base/linuxutils/lsblk/lsblk.go:185]: here we should say unable to find by SN and drive.Path

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 11]
```diff
@@ -175,20 +170,18 @@ func (l *LSBLK) SearchDrivePath(drive *api.Drive) (string, error) {
...
-		errMsg := fmt.Errorf("unable to find drive path by SN %s, VID %s, PID %s", sn, vid, pid)
-		return "", errMsg
+	// device path might be already set by hwmgr
+	if drive.Path != "" {
+		l.log.Warnf("unable to find a drive path by a given SN: %s, using a drive path: %s", sn, drive.Path)
+		return drive.Path, nil
 	}
 
-	return device, nil
+	errMsg := fmt.Errorf("unable to find drive path by a SN %s and a drive path", sn)
```
Comment (katarzyna-kulpa) [inline pkg/base/linuxutils/lsblk/lsblk.go:185]: maybe that slogan is better? "unable to find drive path by a SN %s or in DriveCR?"

**Review by katarzyna-kulpa — APPROVED** [review]

**Review by rafalw82 — APPROVED** [review]

**Review by mishoyama — APPROVED** [review]
