### PR TITLE
[ISSUE-761] Scheduler respect labeled node

### LINKED ISSUE #371: Code refactoring after reservation logic change
There are multiple places marked in the code that should be refactored or improved after reservation logic change.

### LINKED ISSUE #761: Scheduler extender doesn't respect node labels
**Describe the bug**
Scheduler extender doesn't respect node labels

**To Reproduce**
Label nodes 
kubectl label node <> app=csi-baremetal
Deploy CSI with the label
Deployment of test application stuck because of the following errors in the logs:
```
Jan 13 15:11:28.585 [ERRO] [Extender] failed to get NodeID: annotation nodes.csi-baremetal.dell.com/uuid hadn't been set for node vcloud-csi-worker25
Jan 13 15:11:28.585 [ERRO] [Extender] failed to get NodeID: annotation nodes.csi-baremetal.dell.com/uuid hadn't been set for node vcloud-csi-worker29
Jan 13 15:11:28.585 [ERRO] [Extender] failed to get NodeID: annotation nodes.csi-baremetal.dell.com/uuid hadn't been set for node vcloud-csi-worker40
```

**Expected behavior**
Scheduler respect labeled node

### PR DESCRIPTION
**Pull request by rkiselenko**
### Resolves #371

- Fix for scheduler extender doesn't respect node labels
- Recover commented tests for scheduler

## PR checklist
- [x] Add link to the issue
- [x] Choose Project
- [x] Choose PR label
- [x] New unit tests added
- [x] Modified code has meaningful comments
- [x] All TODOs are linked with the issues
- [x] All comments are resolved

## Testing

Testing in issue #761

### CODE REVIEW

File: pkg/scheduler/extender/extender.go [hunk 1]
```diff
@@ -424,10 +424,9 @@ func (e *Extender) createReservation(ctx context.Context, namespace string, name
 
 	// fill in node requests
 	reservation.NodeRequests = &genV1.NodeRequests{}
-	if nodes, err := e.prepareListOfRequestedNodes(nodes); err == nil {
-		reservation.NodeRequests.Requested = nodes
-	} else {
-		return err
+	reservation.NodeRequests.Requested = e.prepareListOfRequestedNodes(nodes)
+	if len(reservation.NodeRequests.Requested) == 0 {
+		return fmt.Errorf("createReservation: list of requested nodes is empty, incoming nodes count: %d", len(nodes))
```
Comment (safronovD) [inline pkg/scheduler/extender/extender.go:429]: Will this error be returned in `filter` function? Here we set error on FilterRequest response - https://github.com/dell/csi-baremetal/blob/81b899af27f794acbc9d0a6c9c787593a2fe74b9/pkg/scheduler/extender/extender.go#L125. After error kube-sceduler will not send requests anymore

Comment (rkiselenko) [reply pkg/scheduler/extender/extender.go:429]: If there is no nodes how should filter behave ?

Comment (safronovD) [reply pkg/scheduler/extender/extender.go:429]: In my opinion we should return just empty list, not error in main `FilterHandler`?

Comment (safronovD) [reply pkg/scheduler/extender/extender.go:429]: @mishoyama any suggestion?

File: pkg/scheduler/extender/extender.go [hunk 2]
```diff
@@ -447,20 +446,20 @@ func (e *Extender) createReservation(ctx context.Context, namespace string, name
...
-	for i, node := range nodes {
-		node := node
-		nodeID, err := annotations.GetNodeID(&node, e.annotationKey, e.featureChecker)
+	for _, node := range nodes {
+		n := node
+		nodeID, err := annotations.GetNodeID(&n, e.annotationKey, e.featureChecker)
 		if err != nil {
-			e.logger.Errorf("failed to get NodeID: %s", err)
-			return nil, err
+			e.logger.Errorf("node:%s cant get NodeID error: %s", n.Name, err)
```
Comment (mishoyama) [inline pkg/scheduler/extender/extender.go:456]: We need to check node label here. When node has label which was set during CSI installation need to return an error, otherwise just skip such node without even logging error.

File: pkg/scheduler/extender/extender.go (hunk 1 above)
Comment (mishoyama) [reply pkg/scheduler/extender/extender.go:429]: No need to return error - we just don't have appropriate nodes for scheduling at the current moment.

**Review by mishoyama — CHANGES_REQUESTED** [review]

File: pkg/scheduler/extender/extender.go (hunk 2 above)
Comment (rkiselenko) [reply pkg/scheduler/extender/extender.go:456]: Could you explain a little, I don't get.

File: pkg/scheduler/extender/extender.go (hunk 1 above)
Comment (rkiselenko) [reply pkg/scheduler/extender/extender.go:429]: 👍

File: pkg/scheduler/extender/extender.go (hunk 2 above)
Comment (mishoyama) [reply pkg/scheduler/extender/extender.go:456]: When you deploy CSI on subset of nodes using labels you will always get this error for nodes which don't have them. It sounds logical to let extender know which labels are used and don't event try to get node UUID for them.

Comment (rkiselenko) [reply pkg/scheduler/extender/extender.go:456]: 👍

**Comment by rkiselenko** [comment]
/ci
operator_branch='feature-issue-761-labeled-nodes-bug'

**Comment by rkiselenko** [comment]
/ci
operator_branch='feature-issue-761-labeled-nodes-bug'

**Review by safronovD — APPROVED** [review]

**Review by yurkov-anton — APPROVED** [review]

**Review by mishoyama — APPROVED** [review]
