### PR TITLE
[Issue: 1104] model name with empty spaces

### LINKED ISSUE #1104: Disk model not found
**Describe the bug**
When disk model has two empty spaces inside the model name, cis baremetal is unable to match it with driveCR. 

**Environment (please complete the following information):**
all
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by katarzyna-kulpa**
### Resolves #1104 (https://github.com/dell/csi-baremetal/issues/1104)

Correctly match drives  when hal mgr returns model with double empty spaces inside model name

## PR checklist
- [ ] Add link to the issue
- [ ] Choose Project
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
Full regression

### CODE REVIEW

**Review by rafalw82 — APPROVED** [review]

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 1]
```diff
@@ -175,7 +175,7 @@ func (l *LSBLK) SearchDrivePath(drive *api.Drive) (string, error) {
 	for _, l := range lsblkOut {
 		lvid := strings.TrimSpace(l.Vendor)
 		if strings.EqualFold(l.Serial, sn) && strings.EqualFold(lvid, vid) &&
```
Comment (mishoyama) [inline pkg/base/linuxutils/lsblk/lsblk.go:177]: I think we need to add comments here - why comparison is done this way.

Comment (katarzyna-kulpa) [reply pkg/base/linuxutils/lsblk/lsblk.go:177]: Do these comments work?
// Compare drive's sn, vid, pid with lsblk output.
// The hasPrefixIgnoreSpaces function is used to compare pid and lsblk model, accounting for drives that may have
// multiple spaces in their pid, and situations where pid is truncated or limited to 16 digits compared to lsblk model.

or something shorter/longer?

Comment (mishoyama) [reply pkg/base/linuxutils/lsblk/lsblk.go:176]: Looks good, thank you!

**Review by mishoyama — APPROVED** [review]
