### PR TITLE
Finding drive vid in lsblk vendor

### LINKED ISSUE #1095: Value of disk vendor id differs between HAL and output from lsblk.
**Describe the bug**

**Environment (please complete the following information):**
 - Hardware: [e.g. Dell PowerEdge]
 - OS: [e.g. Ubuntu, run `printf "$(uname -srm)\n$(cat /etc/os-release)\n"`]
 - Version: [e.g. 1.0.0]

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by prasant123**
## PR checklist
- [x] Add link to the issue
- [ ] Choose Project
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
_Provide test details_

### CODE REVIEW

**Review by eddiepavkovic — APPROVED** [review]
I'm good with the change as it was discussed with @mishoyama

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 1]
```diff
@@ -178,7 +173,7 @@ func (l *LSBLK) SearchDrivePath(drive *api.Drive) (string, error) {
 	vid := drive.VID
 	pid := drive.PID
 	for _, l := range lsblkOut {
-		if strings.EqualFold(l.Serial, sn) && strings.EqualFold(l.Vendor, vid) &&
+		if strings.EqualFold(l.Serial, sn) && strings.Contains(l.Vendor, vid) &&
```
Comment (libzhang) [inline pkg/base/linuxutils/lsblk/lsblk.go:176]: how about the pid handling ?  lsblk returned "HGST HUS728T8TALE6L0",  but the drive CR value is from drivemgr,  which is "HGST HUS728T8TAL". 
and also is there possibility that Serinal need same handling with Vendor,  as Serialnumber may also contain some trailing space.

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 2]
```diff
@@ -161,11 +161,6 @@ func (l *LSBLK) GetBlockDevices(device string) ([]BlockDevice, error) {
 // Receives an instance of drivecrd.Drive struct
```
Comment (libzhang) [inline pkg/base/linuxutils/lsblk/lsblk.go:161]: one general comments is to create an issue first and link the issue to the PR.  and put [ISSUE-xxx] in PR title.

Comment (prasant123) [reply pkg/base/linuxutils/lsblk/lsblk.go:161]: Addressed

File: pkg/base/linuxutils/lsblk/lsblk.go (hunk 1 above)
Comment (prasant123) [reply pkg/base/linuxutils/lsblk/lsblk.go:176]: We are observing failure only for the Vendo ID. Since the serial number reported by both HAL and lsblk are the same, we should be good with the existing implementation. We need a quick resolution due to the time constraint, however I agree that we need to have a relook at this area of code in the next release cycle

Comment (libzhang) [reply pkg/base/linuxutils/lsblk/lsblk.go:176]: do you mean for the pid I mentioned above,  for different length strings,   strings.EqualFold will return true in the case ?

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 3]
```diff
@@ -178,7 +173,7 @@ func (l *LSBLK) SearchDrivePath(drive *api.Drive) (string, error) {
 	vid := drive.VID
 	pid := drive.PID
 	for _, l := range lsblkOut {
-		if strings.EqualFold(l.Serial, sn) && strings.EqualFold(l.Vendor, vid) &&
+		if strings.EqualFold(l.Serial, sn) && strings.Contains(l.Vendor, vid) &&
 			strings.EqualFold(l.Model, pid) {
```
Comment (yanxiucai) [inline pkg/base/linuxutils/lsblk/lsblk.go:177]: Need code change here to handle the PID.
In our test, for the same disk, the VID and PID format is different from lsblk and drive CR. 

 l.Vendor  is  "ATA     " while  vid (drive.VID) is “ATA”
l.Model  is "HGST HUS728T8TALE6L0" while pid (drive.PID) is “HGST HUS728T8TAL”

File: pkg/base/linuxutils/lsblk/lsblk.go (hunk 1 above)
Comment (yanxiucai) [reply pkg/base/linuxutils/lsblk/lsblk.go:176]: I think we should only ignore the trailing space in this JIRA. It is not safe to use "string.contains(A, B)" as it will also return TRUE for many other cases. For example:  A = "testing   "    B="ing"

File: pkg/base/linuxutils/lsblk/lsblk.go (hunk 3 above)
Comment (prasant123) [reply pkg/base/linuxutils/lsblk/lsblk.go]: Agree!
Updated the changes, please take a look

File: pkg/base/linuxutils/lsblk/lsblk.go [hunk 4]
```diff
@@ -178,8 +174,9 @@ func (l *LSBLK) SearchDrivePath(drive *api.Drive) (string, error) {
 	vid := drive.VID
 	pid := drive.PID
 	for _, l := range lsblkOut {
-		if strings.EqualFold(l.Serial, sn) && strings.EqualFold(l.Vendor, vid) &&
-			strings.EqualFold(l.Model, pid) {
+		lvid := strings.TrimSpace(l.Vendor)
+		if strings.EqualFold(l.Serial, sn) && strings.EqualFold(lvid, vid) &&
+			strings.HasPrefix(l.Model, pid) {
```
Comment (libzhang) [inline pkg/base/linuxutils/lsblk/lsblk.go:179]: basically, it is ok. 
just noted that: if pid is null string(""),  then strings.HasPrefix will also return true.  but in our case,  pid seems to not able to be null. we may need re-look at this code in later release as well.

**Review by lordjun — APPROVED** [review]

**Comment by lordjun** [comment]
Please go ahead to merge the code, Prasant. Thanks.
