### PR TITLE
[ISSUE-999] disk taint label sync when ac removed or label removed

### LINKED ISSUE #999: AvailableCapacity custom resource taint label should keep sync with related drive
**Describe the bug**
1. when AC taint label is removed  or ac is deleted.  ac taint label could not recover even if the related drive taint 
label is still there. 

**Environment (please complete the following information):**
 - Hardware: [e.g. Dell PowerEdge]
 - OS: [e.g. Ubuntu, run `printf "$(uname -srm)\n$(cat /etc/os-release)\n"`]
 - Version: [e.g. 1.0.0]

**To Reproduce**
remove ac taint label  or delete ac

**Expected behavior**
ac label should keep sync with related drive. 

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by libzhang**
### Resolves #999 
1. for non-lvg/lvg cases,  sync ac label when necessary.

**Note**:  there is issue now for lvg cases,  as for lvg ac,  when ac removed,  it's ac could not re-generated. (it seems a day one bug). 

## PR checklist
- [x] Add link to the issue
- [ ] Choose Project
- [ ] Choose PR label
- [x] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
1. removed AvailableCapacity and AC re-generated.    
```bash     
$ kubectl get ac 
NAME                                   SIZE         STORAGE CLASS   LOCATION                               NODE
09cb349c-3a20-47e4-9d4b-ca347cde99c9   369098752    NVMELVG         4ad83990-7736-48be-90b5-43396ee3c34f   515d58b0-5f2f-431b-897f-93fa769843c1
5d59fd13-8020-46b3-a3d3-30965528b0fa   1000000000   NVME            8cb2de9d-380d-4f96-8340-68ebbc2a8724   515d58b0-5f2f-431b-897f-93fa769843c1
835ef385-ee17-433a-891d-1a8aa40eb153                HDD             0aa2245b-5512-472b-958f-2c4e838740f9   515d58b0-5f2f-431b-897f-93fa769843c1
b7ed540c-b116-41b8-8a74-46d0b6f7e4d4   1000000000   NVME            42c98d0b-0f0e-4f8a-b547-012abc06269c   515d58b0-5f2f-431b-897f-93fa769843c1
be4ee1b4-a782-4580-916c-98e254721bb0   1000000000   NVME            c0a7890b-f3f4-4256-8988-7b9c10e56629   515d58b0-5f2f-431b-897f-93fa769843c1

$ kubectl describe drive c0a7890b-f3f4-4256-8988-7b9c10e56629 | grep taint
              drive.csi-baremetal.dell.com/taint=NoSchedule
          f:drive.csi-baremetal.dell.com/taint:

$ kubectl describe ac be4ee1b4-a782-4580-916c-98e254721bb0 | grep taint
              drive.csi-baremetal.dell.com/taint=NoSchedule
          f:drive.csi-baremetal.dell.com/taint:

$ kubectl delete ac be4ee1b4-a782-4580-916c-98e254721bb0
availablecapacity.csi-baremetal.dell.com "be4ee1b4-a782-4580-916c-98e254721bb0" deleted

$ kubectl get ac 
NAME                                   SIZE         STORAGE CLASS   LOCATION                               NODE
09cb349c-3a20-47e4-9d4b-ca347cde99c9   369098752    NVMELVG         4ad83990-7736-48be-90b5-43396ee3c34f   515d58b0-5f2f-431b-897f-93fa769843c1
5d59fd13-8020-46b3-a3d3-30965528b0fa   1000000000   NVME            8cb2de9d-380d-4f96-8340-68ebbc2a8724   515d58b0-5f2f-431b-897f-93fa769843c1
835ef385-ee17-433a-891d-1a8aa40eb153                HDD             0aa2245b-5512-472b-958f-2c4e838740f9   515d58b0-5f2f-431b-897f-93fa769843c1
b7ed540c-b116-41b8-8a74-46d0b6f7e4d4   1000000000   NVME            42c98d0b-0f0e-4f8a-b547-012abc06269c   515d58b0-5f2f-431b-897f-93fa769843c1

$ kubectl get ac  -w
NAME                                   SIZE         STORAGE CLASS   LOCATION                               NODE
09cb349c-3a20-47e4-9d4b-ca347cde99c9   369098752    NVMELVG         4ad83990-7736-48be-90b5-43396ee3c34f   515d58b0-5f2f-431b-897f-93fa769843c1
5d59fd13-8020-46b3-a3d3-30965528b0fa   1000000000   NVME            8cb2de9d-380d-4f96-8340-68ebbc2a8724   515d58b0-5f2f-431b-897f-93fa769843c1
835ef385-ee17-433a-891d-1a8aa40eb153                HDD             0aa2245b-5512-472b-958f-2c4e838740f9   515d58b0-5f2f-431b-897f-93fa769843c1
b7ed540c-b116-41b8-8a74-46d0b6f7e4d4   1000000000   NVME            42c98d0b-0f0e-4f8a-b547-012abc06269c   515d58b0-5f2f-431b-897f-93fa769843c169811509-32b4-4591-b0b2-71d73c8b6610   1000000000   NVME            c0a7890b-f3f4-4256-8988-7b9c10e56629   515d58b0-5f2f-431b-897f-93fa769843c1
^C
$ kubectl describe ac 69811509-32b4-4591-b0b2-71d73c8b6610 | grep taint
              drive.csi-baremetal.dell.com/taint=NoSchedule
          f:drive.csi-baremetal.dell.com/taint:
 ```
 1.2.  removed AvailableCapacity taint label manually.  its taint label should recovered automatically. 
```bash
$ kubectl describe ac 69811509-32b4-4591-b0b2-71d73c8b6610 | grep taint
              drive.csi-baremetal.dell.com/taint=NoSchedule
          f:drive.csi-baremetal.dell.com/taint:

$ kubectl label ac 69811509-32b4-4591-b0b2-71d73c8b6610 drive.csi-baremetal.dell.com/taint-
availablecapacity.csi-baremetal.dell.com/69811509-32b4-4591-b0b2-71d73c8b6610 labeled

$ kubectl describe ac 69811509-32b4-4591-b0b2-71d73c8b6610 | grep taint
$ 
$ kubectl describe ac 69811509-32b4-4591-b0b2-71d73c8b6610 | grep taint
$
... wait a moments(less than 30 seconds)

$ kubectl describe ac 69811509-32b4-4591-b0b2-71d73c8b6610 | grep taint
              drive.csi-baremetal.dell.com/taint=NoSchedule
          f:drive.csi-baremetal.dell.com/taint:
```

### CODE REVIEW

File: pkg/controller/capacitycontroller/capacitycontroller.go [hunk 1]
```diff
@@ -130,17 +131,18 @@ func (d *Controller) reconcileDrive(ctx context.Context, drive *drivecrd.Drive)
 	case (health != apiV1.HealthGood && health != apiV1.HealthUnknown) ||
 		status != apiV1.DriveStatusOnline ||
 		usage != apiV1.DriveUsageInUse:
-		return d.handleInaccessibleDrive(ctx, drive.Spec)
+		return d.handleInaccessibleDrive(ctx, drive)
```
Comment (yimingwangdell) [inline pkg/controller/capacitycontroller/capacitycontroller.go:134]: do we also need this in LVG?

Comment (libzhang) [reply pkg/controller/capacitycontroller/capacitycontroller.go:134]: no, lvg bad it's size will be reset to 0,  and the related lvg ac could not be used any more.

**Review by yanxiucai — APPROVED** [review]

**Review by CraneShiEMC — APPROVED** [review]
