### PR TITLE
[ISSUE-849] Call vgs refresh after each lvg-disk reinsert

### LINKED ISSUE #849: Ubuntu 20+ base image can't check failed LVs after disk reinsert
**Describe the bug**
After updating base node image to Ubuntu 20 reinserting LVG disk is failed.
LVG recived `VolumeGroupScanInvolved`, but no `VolumeGroupReactivateInvolved`.
Without reactivate volumes have moun failure after recreating pod
```
 volume {'CSIStatus': 'FAILED', 'Health': 'GOOD', 'Id': 'pvc-36f1d3cb-6ee3-47da-9dc5-563e4f381de8', 'Location': '06f7679d-767a-46fc-9a62-498dc10c58f4', 'LocationType': 'LVM', 'Mode': 'FS', 'NodeId': 'ee5f5da5-b9c8-4e3c-8a0d-816c0874d310', 'OperationalStatus': 'OPERATIVE', 'Owners': ['sts-pvc-hddlvg-test-0'], 'Size': 33000783872, 'StorageClass': 'HDDLVG', 'Type': 'xfs', 'Usage': 'IN_USE'} has failed CSIStatus volume {'CSIStatus': 'FAILED', 'Health': 'GOOD', 'Id': 'pvc-7701c1c4-2bd8-4d23-8431-fabb844971ce', 'Location': '06f7679d-767a-46fc-9a62-498dc10c58f4', 'LocationType': 'LVM', 'Mode': 'FS', 'NodeId': 'ee5f5da5-b9c8-4e3c-8a0d-816c0874d310', 'OperationalStatus': 'OPERATIVE', 'Owners': ['sts-pvc-hddlvg-test-0'], 'Size': 33000783872, 'StorageClass': 'HDDLVG', 'Type': 'xfs', 'Usage': 'IN_USE'} has failed CSIStatus volume {'CSIStatus': 'FAILED', 'Health': 'GOOD', 'Id': 'pvc-7cd32612-d371-4147-bbe3-d206ec2f19b4', 'Location': '06f7679d-767a-46fc-9a62-498dc10c58f4', 'LocationType': 'LVM', 'Mode': 'FS', 'NodeId': 'ee5f5da5-b9c8-4e3c-8a0d-816c0874d310', 'OperationalStatus': 'OPERATIVE', 'Owners': ['sts-pvc-hddlvg-test-0'], 'Size': 33000783872, 'StorageClass': 'HDDLVG', 'Type': 'xfs', 'Usage': 'IN_USE'} has failed CSIStatus volume {'CSIStatus': 'FAILED', 'Health': 'UNKNOWN', 'Id': 'pvc-90595e84-4bd1-4e11-818d-a290f0ce6c17', 'Location': '06f7679d-767a-46fc-9a62-498dc10c58f4',... [ Message content over the limit has been removed. ] ...: 'OPERATIVE', 'Owners': ['sts-pvc-hddlvg-test-0'], 'Size': 33000783872, 'StorageClass': 'HDDLVG', 'Type': 'xfs', 'Usage': 'IN_USE'} has failed CSIStatus volume {'CSIStatus': 'FAILED', 'Health': 'UNKNOWN', 'Id': 'pvc-95493d21-410a-46f6-aef1-d67faa42691a', 'Location': '06f7679d-767a-46fc-9a62-498dc10c58f4', 'LocationType': 'LVM', 'Mode': 'FS', 'NodeId': 'ee5f5da5-b9c8-4e3c-8a0d-816c0874d310', 'OperationalStatus': 'OPERATIVE', 'Owners': ['sts-pvc-hddlvg-test-0'], 'Size': 33000783872, 'StorageClass': 'HDDLVG', 'Type': 'xfs', 'Usage': 'IN_USE'} has failed CSIStatus volume {'CSIStatus': 'FAILED', 'Health': 'GOOD', 'Id': 'pvc-b995dca5-0ac2-47bf-abe3-3ea209feb4be', 'Location': '06f7679d-767a-46fc-9a62-498dc10c58f4', 'LocationType': 'LVM', 'Mode': 'FS', 'NodeId': 'ee5f5da5-b9c8-4e3c-8a0d-816c0874d310', 'OperationalStatus': 'OPERATIVE', 'Owners': ['sts-pvc-hddlvg-test-0'], 'Size': 33000783872, 'StorageClass': 'HDDLVG', 'Type': 'xfs', 'Usage': 'IN_USE'} has failed CSIStatus volume {'CSIStatus': 'FAILED', 'Health': 'GOOD', 'Id': 'pvc-c4156e9a-9d75-4380-92a6-4ad7e766ee25', 'Location': '06f7679d-767a-46fc-9a62-498dc10c58f4', 'LocationType': 'LVM', 'Mode': 'FS', 'NodeId': 'ee5f5da5-b9c8-4e3c-8a0d-816c0874d310', 'OperationalStatus': 'OPERATIVE', 'Owners': ['sts-pvc-hddlvg-test-0'], 'Size': 33000783872, 'StorageClass': 'HDDLVG', 'Type': 'xfs', 'Usage': 'IN_USE'} has failed CSIStatus
```

**Environment (please complete the following information):**
 - Hardware: any
 - OS: any

**To Reproduce**
1. Create LVG volume
2. Pull and insert LVG disk

**Expected behavior**
Need to perform refresh after each disk reinsert

### PR DESCRIPTION
**Pull request by safronovD**
### Resolves #849 

- Refactor `VolumeGroupScan...` events. On `checkVGErrors` call:
1. VolumeGroupScanInvolved (ever)
2. VolumeGroupScanFailed/VolumeGroupScanNoErrors/VolumeGroupScanErrorsFound (based on a result)
- Add checking all lvs via lsblk for `checkVGErrors`
- Refactor action after lvg disk OFFLINE->ONLINE:
1. `vgchange --refresh`
2. check io errors

## PR checklist
- [x] Add link to the issue
- [x] Choose Project
- [x] Choose PR label
- [x] New unit tests added
- [x] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
1, Create sts with LVG volumes
```
kubectl apply -f tests/app/nginx-lvg.yaml
```
2. Find node, csibmnode and drive related to one of the volumes
```
hostname1:~ # kubectl get drive -o wide ba6533a0-4c3f-4214-b708-fb5704bbf826 

NAME                                   SIZE            TYPE   HEALTH   STATUS   USAGE    SYSTEM   PATH       SERIAL NUMBER   NODE                                   SLOT

ba6533a0-4c3f-4214-b708-fb5704bbf826   8001000000000   HDD    GOOD     ONLINE   IN_USE            /dev/sdl   VDH1AAND        ebcb42dd-656b-4b37-adb8-b47fe50c3a93   22
```
3. On a node with drive: mask drive via SCSI settings
```
echo 1 > /sys/class/scsi_device/0\:0\:11\:0/device/delete
```
4. Wait drive is in OFFLINE state
```
hostname1:~ # kubectl get drive -o wide ba6533a0-4c3f-4214-b708-fb5704bbf826 

NAME                                   SIZE            TYPE   HEALTH    STATUS    USAGE    SYSTEM   PATH       SERIAL NUMBER   NODE                                   SLOT

ba6533a0-4c3f-4214-b708-fb5704bbf826   8001000000000   HDD    UNKNOWN   OFFLINE   IN_USE            /dev/sdl   VDH1AAND        ebcb42dd-656b-4b37-adb8-b47fe50c3a93   22
```
5. Return drive
```
echo "- - -" > /sys/class/scsi_host/host0/scan
```
6. Wait drive is in ONLINE state
```
hostname1:~ # kubectl get drive -o wide ba6533a0-4c3f-4214-b708-fb5704bbf826 

NAME                                   SIZE            TYPE   HEALTH   STATUS   USAGE    SYSTEM   PATH       SERIAL NUMBER   NODE                                   SLOT

ba6533a0-4c3f-4214-b708-fb5704bbf826   8001000000000   HDD    GOOD     ONLINE   IN_USE            /dev/sdl   VDH1AAND        ebcb42dd-656b-4b37-adb8-b47fe50c3a93   22
```
7. Check LVG events
```
Events:
  Type     Reason                         Age   From                Message
  ----     ------                         ----  ----                -------
  Warning  VolumeGroupReactivateInvolved  105s  csi-baremetal-node  Trying to re-activate volume group
  Normal   VolumeGroupScanInvolved        105s  csi-baremetal-node  Check for IO errors
  Normal   VolumeGroupScanNoErrors        105s  csi-baremetal-node  No errors was found
```
8. Check node logs
```
May 17 14:33:01.670 [ERRO] [VolumeManager] [reactivateVG] [26576579-eb79-4465-af76-b170909b1b14] [pkg/node/volumemgr.go:1080] [reactivateVG] IO errors detected for volume group 26576579-eb79-4465-af76-b170909b1b14

May 17 14:33:01.670 [INFO] [LVM] Trying to re-activate volume group 26576579-eb79-4465-af76-b170909b1b14

May 17 14:33:01.878 [DEBU] [Executor] [/sbin/lvm vgchange --refresh 26576579-eb79-4465-af76-b170909b1b14] [208.351545ms] [208351545] stdout: 

May 17 14:33:01.878 [INFO] [VolumeManager] [checkVGErrors] [26576579-eb79-4465-af76-b170909b1b14] Scan volume group 26576579-eb79-4465-af76-b170909b1b14 for IO errors

May 17 14:33:01.986 [DEBU] [Executor] [/sbin/lvm vgscan] [107.581582ms] [107581582] stdout:   Found volume group "26576579-eb79-4465-af76-b170909b1b14" using metadata type lvm2

  Found volume group "vgSystem" using metadata type lvm2

May 17 14:33:01.997 [INFO] [VolumeManager] [checkVGErrors] [26576579-eb79-4465-af76-b170909b1b14] No IO errors detected for volume group 26576579-eb79-4465-af76-b170909b1b14
```

### CODE REVIEW

File: pkg/node/volumemgr.go [hunk 1]
```diff
@@ -1037,6 +1022,72 @@ func (m *VolumeManager) handleDriveStatusChange(ctx context.Context, drive updat
...
+func (m *VolumeManager) checkVGErrors(lvg *lvgcrd.LogicalVolumeGroup, drivePath string) {
+	ll := m.log.WithFields(logrus.Fields{
+		"method": "checkVGErrors",
+		"LVG":    lvg.Name,
+	})
+
+	ll.Infof("Scan volume group %s for IO errors", lvg.Name)
+	m.recorder.Eventf(lvg, eventing.VolumeGroupScanInvolved, "Check for IO errors")
+
+	ok, err := m.lvmOps.VGScan(lvg.Name)
```
Comment (mishoyama) [inline pkg/node/volumemgr.go:1034]: `ok` and `err` names look confusing.

Comment (safronovD) [reply pkg/node/volumemgr.go]: renamed

File: pkg/node/volumemgr.go [hunk 2]
```diff
@@ -1037,6 +1022,72 @@ func (m *VolumeManager) handleDriveStatusChange(ctx context.Context, drive updat
...
+	if err != nil {
+		ll.Errorf("Failed to scan volume group %s for IO errors: %v", lvg.Name, err)
+		m.recorder.Eventf(lvg, eventing.VolumeGroupScanFailed, err.Error())
+		return
+	}
+	if ok {
```
[the remark this answers is not in the document]
Comment (safronovD) [reply pkg/node/volumemgr.go]: I would like to separate cases:
- vgscan found IO errors
- failure while calling vgscan

**Review by mishoyama — APPROVED** [review]

**Review by yurkov-anton — APPROVED** [review]
